#!/bin/bash
#
#$ -N extractSRA
#$ -pe 12way 12 
#$ -q normal
#$ -o extractSRA.o$JOB_ID
#$ -l h_rt=24:00:00
#$ -V
#$ -cwd
#$ -A Exosome-RNA-seq
#------------------------------------------------------
module load launcher  gcc/4.7.1 bedtools sratoolkit
export EXECUTABLE=$TACC_LAUNCHER_DIR/init_launcher 
export CONTROL_FILE=/home1/02727/cdw2854/plasmaDNAseq/plasmaScripts/prepareData/command.sh
export WORKDIR=/scratch/02727/cdw2854/TGIRT_plasma_dna/plasmaResults/data

cd $WORKDIR

$TACC_LAUNCHER_DIR/paramrun $EXECUTABLE $CONTROL_FILE

